### ISSUE TITLE
Issues by converting my app into a package

### ISSUE THREAD

**Issue by melvand** [daattali/colourpicker#38] opened 2019-12-17 15:43 UTC
Colourpicker is a really great tool for Shiny applications and I'm using it for the first time in an app. It is working great in the app, but when i try to "convert" my app into a package, everything is working fine except for the colourInput function. No error but it lead to a white rectangle.

Any idea what caused it?
I attach a basic version of the app package, in case it's helpfull.

Thanks in advance,
[shinyAppDemo_0.1.0.zip](https://github.com/daattali/colourpicker/files/3974100/shinyAppDemo_0.1.0.zip)

**Comment by daattali** [comment] 2019-12-18 07:17
Hi, I'm not sure how to use the zip file you sent me. If you could please create a minimal example that only includes the files that are absolutely necessary, that would help.

**Comment by ChristopherBarrington** [comment] 2020-05-17 08:04
Hello @daattali,

I am having the same problem and have been tearing my hair out! When I use devtools::load_all() during development everything works fine in my package. If I use `devtools::install_local` or `devtools::install_git()` the `colourInput` boxes are white as described above.

I downloaded the package in the original post and installed as follows. When I load with `library(shinyAppDemo)` after restarting R Studio the colourInput box is blank.

```r
devtools::install_local('~/Downloads/shinyAppDemo_0.1.0.zip', dependencies=FALSE, force=TRUE)
shinyAppDemo::launchApp()
```

**Comment by ChristopherBarrington** [comment] 2020-05-17 08:59
I think this was due (in my case) to UI elements being defined outside the shinyAppUI function then being assembled into a shiny UI. By putting all of my elements into the shinyAppUI function (as in the example code!!) the problem seems to be resolved. Though I am still confused as to why it works with `load_all`. From my perspective, I think it can be closed - user error!

**Comment by daattali** [comment] 2020-08-19 07:58
Closing this issue due to non reproducibility. If someone can find an issue feel free to open a bug report again

**Closed as completed by daattali** 2020-08-19 07:58 UTC

**Comment by daattali** [comment] 2022-10-31 18:36
It's been a very long time but I think I finally understand the problem and fixed it. If either of you is still on GitHub and still has their old code - you can try again using the latest version and let me know if it now works.

I would really appreciate knowing if this is fixed for you, but I completely understand if you no longer have your old code!
